import myheader from "./myHeader"
import myFooter from "./myFooter"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header style={{backgroundColor : "black" , 
    color:"white"}}>
        {myheader()}
      </header>
        {children}
      <footer style={{backgroundColor:"black" , color:"white"}}>
        {myFooter()}
      </footer>
      </body>
    </html>
  )
}
